version: "3"

services:
  be-device-query:
    container_name: be-device-query
    image: device-query-tool-be
    restart: always
    tty: true
    stdin_open: true
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - device_query_db
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
    environment:
      POSTGRES_DB_USER: postgres
      POSTGRES_DB_HOST: device_query_db
      POSTGRES_DB_NAME: device_query_development
      RAILS_ENV: development

  device_query_db:
    container_name: device_query_db
    restart: always
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - device_query_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: device_query_development
      POSTGRES_HOST_AUTH_METHOD: "trust"
volumes:
  device_query_db_volume:
    external: true

