development:
  adapter: postgresql
  host: localhost
  database: dq_development
  port: 5432

test:
  adapter: postgresql
  host: localhost
  database: dq_test
  port: 5432

production:
  adapter: postgresql
  host: localhost
  database: dq_production
  port: 5432c
